(()=>{
'use strict';

let activeTourId='';
let opsTab='participants';
let showArchived=false;
const B=()=>window.ChanaBackend;
const U=()=>window.ChanaUI;
const crm=()=>B()?.state?.crm||{travelers:[],participants:[],payments:[],bookingGroups:[],rooms:[],roomOccupants:[],followUps:[],tasks:[],documents:[],contactLog:[],loaded:false};
const e=s=>U()?.esc?U().esc(s):String(s??'').replace(/[&<>'"]/g,'');
const fmt=d=>U()?.fmt?U().fmt(d):String(d||'');
const money=(n,c='ILS')=>n==null||n===''?'':new Intl.NumberFormat('he-IL',{style:'currency',currency:c,maximumFractionDigits:0}).format(Number(n)||0);
const moneyMap=m=>Object.entries(m||{}).filter(([,v])=>Number(v)>0).map(([c,v])=>money(v,c)).join(' · ')||'—';
const dt=s=>{if(!s)return'';try{return new Intl.DateTimeFormat('he-IL',{dateStyle:'short',timeStyle:'short'}).format(new Date(s));}catch(_){return s;}};
const statusText=s=>({interested:'מתעניין/ת',contacted:'נוצר קשר',pending:'בתהליך הרשמה',registered:'נרשם/ה',deposit:'שולם חלקית',paid:'שולם',waitlist:'רשימת המתנה',cancelled:'בוטל'}[s]||s||'');
const paymentMethod=s=>({bank_transfer:'העברה בנקאית',cash:'מזומן',supplier:'תשלום אצל הספק',check:'צ׳ק',other:'אחר'}[s]||s||'');
const roomType=s=>({single:'יחיד',double:'זוגי',twin:'טווין',triple:'טריפל',family:'משפחה',other:'אחר'}[s]||s||'');
const taskKind=s=>({follow_up:'חזרה למטייל',payment:'תשלום',documents:'מסמכים',supplier:'ספק',other:'אחר'}[s]||s||'');
const contactChannel=s=>({phone:'טלפון',whatsapp:'WhatsApp',email:'אימייל',note:'הערה פנימית',in_person:'פנים אל פנים'}[s]||s||'');
const contactDirection=s=>({outbound:'יצא מחנה',inbound:'התקבל',internal:'פנימי'}[s]||s||'');
const findTraveler=id=>crm().travelers.find(x=>x.id===id);
const findParticipant=id=>crm().participants.find(x=>x.id===id);
const findTour=(d,id)=>d.tours.find(x=>x.id===id);
const activeTours=d=>d.tours.filter(t=>!t.sourceOnly&&!t.archived).sort((a,b)=>String(a.start||'9999').localeCompare(String(b.start||'9999')));
const ensureTour=d=>{const list=activeTours(d);if(!activeTourId||!list.some(t=>t.id===activeTourId))activeTourId=list[0]?.id||'';return activeTourId;};
const paidFor=pid=>{const p=findParticipant(pid),currency=p?.currency;return crm().payments.filter(x=>x.participantId===pid&&(!currency||x.currency===currency)).reduce((s,x)=>s+Number(x.amount||0),0);};
const roomFor=pid=>{const occ=crm().roomOccupants.find(x=>x.participantId===pid);return occ?crm().rooms.find(r=>r.id===occ.roomId):null;};
const groupFor=id=>crm().bookingGroups.find(g=>g.id===id);
const participantCountForTraveler=id=>crm().participants.filter(p=>p.travelerId===id&&p.status!=='cancelled').length;
const participantName=p=>findTraveler(p.travelerId)?.fullName||'מטייל/ת';
const normalizeWa=phone=>{let n=String(phone||'').replace(/\D/g,'');if(n.startsWith('0'))n='972'+n.slice(1);return n;};
const localDateTimeInput=(date=new Date())=>{const d=new Date(date.getTime()-date.getTimezoneOffset()*60000);return d.toISOString().slice(0,16);};
function refresh(){U()?.renderAdmin?.();}
function toast(x){U()?.toast?.(x);}
function modal(x){U()?.openModal?.(x);}
function close(){U()?.closeModal?.();}

function loading(){return `<section class="panel crm-loading"><strong>טוען את מאגר המטיילים…</strong><p class="muted">המידע האישי נטען רק לאחר כניסה מאובטחת ואינו נשמר במטמון הציבורי.</p></section>`;}

function dashboardSummary(d){
  const c=crm(); if(!c.loaded)return '';
  const today=new Date(); today.setHours(23,59,59,999);
  const overdue=c.followUps.filter(x=>x.status==='pending'&&new Date(x.dueAt)<=today).length;
  const fresh=(d.leads||[]).filter(x=>(x.status||'new')==='new').length;
  const balancePeople=c.participants.filter(p=>p.status!=='cancelled'&&p.agreedPrice!=null&&paidFor(p.id)<Number(p.agreedPrice)).length;
  const registered=c.participants.filter(p=>['registered','deposit','paid'].includes(p.status)).length;
  return `<section class="crm-dashboard panel"><div class="panel-head"><div><span class="section-kicker">תפעול הטיולים</span><h3>מה דורש תשומת לב עכשיו</h3></div><button class="btn btn-soft btn-small" data-admin-section="operations">לניהול טיול</button></div><div class="crm-action-kpis"><button data-admin-section="leads"><strong>${fresh}</strong><span>פניות חדשות</span></button><button data-admin-section="operations"><strong>${overdue}</strong><span>מעקבים להיום</span></button><button data-admin-section="operations"><strong>${balancePeople}</strong><span>עם יתרה פתוחה</span></button><button data-admin-section="travelers"><strong>${registered}</strong><span>נרשמים פעילים</span></button></div></section>`;
}
function decorateAdmin(d){
  if(document.querySelector('.admin-welcome')&&!document.querySelector('.crm-dashboard')){
    const q=document.querySelector('.quick-grid');if(q)q.insertAdjacentHTML('afterend',dashboardSummary(d));
  }
  // Add a one-click conversion action to website leads.
  document.querySelectorAll('.lead-card').forEach(card=>{
    if(card.querySelector('[data-action="convert-lead"]'))return;
    const anchor=card.querySelector('[data-action="copy-lead"],[data-action="lead-whatsapp"],[data-action="delete-lead"]');
    const id=anchor?.dataset?.id;if(!id)return;
    const lead=(d.leads||[]).find(x=>x.id===id);if(!lead||lead.status==='converted')return;
    const actions=card.querySelector('.actions');
    if(actions)actions.insertAdjacentHTML('afterbegin',`<button class="btn btn-gold btn-small" data-action="convert-lead" data-id="${e(id)}">הפוך למטייל</button>`);
  });
}

function renderTravelers(d){
  const c=crm();if(!c.loaded)return loading();
  const active=c.travelers.filter(x=>!x.archived),archived=c.travelers.filter(x=>x.archived),people=showArchived?archived:active;
  const returning=active.filter(x=>participantCountForTraveler(x.id)>=2).length;
  const marketing=active.filter(x=>x.marketingConsent).length;
  const table=people.length?people.map(t=>{const trips=participantCountForTraveler(t.id);const search=[t.fullName,t.phone,t.email,t.city,(t.tags||[]).join(' ')].join(' ').toLowerCase();return `<tr data-traveler-row data-search="${e(search)}"><td><strong>${e(t.fullName)}</strong>${t.marketingConsent?'<small class="crm-mini-badge">מאשר/ת עדכונים</small>':''}</td><td><a class="crm-phone" href="tel:${e(t.phone)}">${e(t.phone)}</a></td><td><strong>${trips}</strong>${trips>=2?'<small> חוזר/ת</small>':''}</td><td><span>${e(t.city||'')}</span>${t.email?`<small>${e(t.email)}</small>`:''}</td><td><div class="actions"><button class="btn btn-soft btn-small" data-crm-action="traveler-whatsapp" data-id="${t.id}">WhatsApp</button><button class="btn btn-primary btn-small" data-crm-action="traveler-profile" data-id="${t.id}">כרטיס מטייל</button><button class="btn btn-soft btn-small" data-crm-action="edit-traveler" data-id="${t.id}">עריכה</button>${t.archived?`<button class="btn btn-gold btn-small" data-crm-action="restore-traveler" data-id="${t.id}">החזרה למאגר</button><button class="btn btn-danger btn-small" data-crm-action="erase-traveler" data-id="${t.id}">מחיקה מלאה</button>`:`<button class="btn btn-outline btn-small" data-crm-action="add-participant" data-traveler-id="${t.id}">שייך לטיול</button><button class="btn btn-danger btn-small" data-crm-action="archive-traveler" data-id="${t.id}">ארכיון</button>`}</div></td></tr>`;}).join(''):`<tr><td colspan="5"><div class="empty-state">${showArchived?'הארכיון ריק.':'המאגר עדיין ריק. פנייה מהאתר יכולה להפוך למטייל בלחיצה אחת.'}</div></td></tr>`;
  return `<div class="panel-head"><div><span class="section-kicker">CRM מטיילים</span><h1>מאגר המטיילים</h1><p class="muted">כל אדם נשמר פעם אחת ויכול להיות משויך לכמה טיולים. אין צורך להקליד אותו מחדש.</p></div><div class="actions"><button class="btn btn-outline" data-crm-action="export-travelers">Excel מטיילים</button><button class="btn btn-outline" data-crm-action="export-crm-backup">גיבוי Excel מלא</button><button class="btn btn-gold" data-crm-action="add-traveler">+ מטייל חדש</button></div></div><div class="admin-summary-line"><span><strong>${active.length}</strong> במאגר</span><span><strong>${returning}</strong> מטיילים חוזרים</span><span><strong>${marketing}</strong> אישרו עדכונים</span><span><strong>${archived.length}</strong> בארכיון</span></div><section class="panel"><div class="crm-toolbar"><input type="search" id="travelerSearch" placeholder="חיפוש לפי שם, טלפון, אימייל או עיר" autocomplete="off"><button class="btn ${showArchived?'btn-gold':'btn-soft'}" data-crm-action="toggle-archive">${showArchived?'חזרה למאגר הפעיל':'הצגת ארכיון'}</button><button class="btn btn-soft" data-crm-action="refresh-crm">רענון</button></div><div class="table-wrap"><table class="table crm-table"><thead><tr><th scope="col">מטייל/ת</th><th scope="col">טלפון</th><th scope="col">טיולים</th><th scope="col">פרטים</th><th scope="col">פעולות</th></tr></thead><tbody>${table}</tbody></table></div></section><div class="privacy-guardrail"><strong>שומרים רק מה שצריך.</strong> אין במערכת שדות למספר כרטיס אשראי, CVV או סיסמאות בנקאיות. מסמכים ופרטים רגישים נשמרים רק אם באמת נדרשים ובאזור הפרטי.</div>`;
}

function tourSelect(d){const list=activeTours(d),id=ensureTour(d);return `<select id="crmTourSelect">${list.map(t=>`<option value="${e(t.id)}" ${t.id===id?'selected':''}>${e(t.title)} · ${fmt(t.start)}</option>`).join('')}</select>`;}
function tourStats(d,tourId){
  const c=crm(),ps=c.participants.filter(p=>p.tourId===tourId),active=ps.filter(p=>p.status!=='cancelled'),registered=ps.filter(p=>['registered','deposit','paid'].includes(p.status)),paid=ps.filter(p=>p.status==='paid'),wait=ps.filter(p=>p.status==='waitlist'),paidTotals={},balanceTotals={};
  active.forEach(p=>{const cur=p.currency||'ILS',got=paidFor(p.id);paidTotals[cur]=(paidTotals[cur]||0)+got;if(p.agreedPrice!=null)balanceTotals[cur]=(balanceTotals[cur]||0)+Math.max(0,Number(p.agreedPrice)-got);});
  const t=findTour(d,tourId),capacity=Number(t?.capacity||0),remaining=capacity?Math.max(0,capacity-active.length):null;
  return `<div class="trip-kpis"><div><strong>${active.length}${capacity?`/${capacity}`:''}</strong><span>משתתפים</span></div><div><strong>${registered.length}</strong><span>נרשמו</span></div><div><strong>${paid.length}</strong><span>שולם במלואו</span></div><div><strong>${wait.length}</strong><span>רשימת המתנה</span></div><div><strong>${moneyMap(paidTotals)}</strong><span>תשלומים שנרשמו</span></div><div><strong>${moneyMap(balanceTotals)}</strong><span>יתרות למעקב</span></div>${remaining!==null?`<div><strong>${remaining}</strong><span>מקומות למעקב</span></div>`:''}</div>`;
}
function opsTabs(){return `<div class="admin-tabs crm-ops-tabs">${[['participants','נרשמים'],['payments','תשלומים'],['rooming','חדרים'],['followups','מעקבים'],['tasks','משימות'],['documents','מסמכים']].map(([k,l])=>`<button class="${opsTab===k?'active':''}" data-crm-action="ops-tab" data-tab="${k}">${l}</button>`).join('')}</div>`;}

function participantRows(d,tourId){const c=crm(),ps=c.participants.filter(p=>p.tourId===tourId);if(!ps.length)return `<div class="empty-state">עדיין אין מטיילים משויכים לטיול הזה.</div>`;return `<div class="table-wrap"><table class="table crm-table"><thead><tr><th>מטייל/ת</th><th>סטטוס</th><th>כספים</th><th>חדר/איסוף</th><th>פעולות</th></tr></thead><tbody>${ps.map(p=>{const t=findTraveler(p.travelerId)||{},paid=paidFor(p.id),bal=p.agreedPrice==null?null:Math.max(0,Number(p.agreedPrice)-paid),room=roomFor(p.id),group=groupFor(p.bookingGroupId);return `<tr><td><strong>${e(t.fullName||'')}</strong><small>${e(t.phone||'')}</small>${group?`<small>${e(group.name)}</small>`:''}</td><td><select class="crm-status-select" data-participant-status="${p.id}">${['interested','contacted','pending','registered','deposit','paid','waitlist','cancelled'].map(s=>`<option value="${s}" ${p.status===s?'selected':''}>${statusText(s)}</option>`).join('')}</select></td><td>${p.agreedPrice!=null?`<strong>${money(paid,p.currency)}</strong><small>מתוך ${money(p.agreedPrice,p.currency)}</small>${bal?`<small class="balance-open">יתרה ${money(bal,p.currency)}</small>`:'<small class="balance-ok">אין יתרה</small>'}`:'<span class="muted">לא הוגדר מחיר</span>'}</td><td>${room?`<strong>${e(room.roomLabel)}</strong><small>${roomType(room.roomType)}</small>`:'<span class="muted">ללא חדר</span>'}${p.pickupPoint?`<small>${e(p.pickupPoint)}</small>`:''}</td><td><div class="actions"><button class="btn btn-soft btn-small" data-crm-action="participant-whatsapp" data-id="${p.id}">WhatsApp</button><button class="btn btn-soft btn-small" data-crm-action="edit-participant" data-id="${p.id}">פרטים</button><button class="btn btn-gold btn-small" data-crm-action="add-payment" data-id="${p.id}">תשלום</button><button class="btn btn-outline btn-small" data-crm-action="assign-room" data-id="${p.id}">חדר</button><button class="btn btn-outline btn-small" data-crm-action="add-followup" data-participant-id="${p.id}">מעקב</button></div></td></tr>`}).join('')}</tbody></table></div>`;}
function paymentsPanel(tourId){const c=crm(),ids=new Set(c.participants.filter(p=>p.tourId===tourId).map(p=>p.id)),rows=c.payments.filter(x=>ids.has(x.participantId)).sort((a,b)=>String(b.paidOn).localeCompare(String(a.paidOn)));return `<div class="panel-head"><div><h3>יומן תשלומים ידני</h3><p class="muted">למעקב בלבד. לא מתבצעת כאן סליקה ולא נשמרים פרטי כרטיס.</p></div><button class="btn btn-outline btn-small" data-crm-action="export-tour" data-tour-id="${e(tourId)}">Excel מלא לטיול</button></div>${rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>מטייל/ת</th><th>סכום</th><th>תאריך</th><th>אופן</th><th>אסמכתא</th><th></th></tr></thead><tbody>${rows.map(x=>{const p=findParticipant(x.participantId);return `<tr><td>${e(p?participantName(p):'')}</td><td><strong>${money(x.amount,x.currency)}</strong></td><td>${fmt(x.paidOn)}</td><td>${paymentMethod(x.method)}</td><td>${e(x.reference||'')}</td><td><button class="btn btn-danger btn-small" data-crm-action="delete-payment" data-id="${x.id}">מחיקה</button></td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty-state">עדיין לא נרשמו תשלומים לטיול.</div>'}`;}
function roomingPanel(tourId){const c=crm(),rooms=c.rooms.filter(r=>r.tourId===tourId);return `<div class="panel-head"><div><h3>Rooming List</h3><p class="muted">שיבוץ חדרים מסודר שאפשר לייצא לספק.</p></div><button class="btn btn-gold btn-small" data-crm-action="add-room" data-tour-id="${e(tourId)}">+ חדר</button></div>${rooms.length?`<div class="room-grid">${rooms.map(r=>{const occ=c.roomOccupants.filter(o=>o.roomId===r.id).map(o=>findParticipant(o.participantId)).filter(Boolean);return `<article class="room-card"><div><strong>${e(r.roomLabel)}</strong><span>${roomType(r.roomType)}</span></div><p>${occ.length?occ.map(p=>e(participantName(p))).join(' · '):'עדיין לא שובצו מטיילים'}</p>${r.notes?`<small>${e(r.notes)}</small>`:''}<div class="actions"><button class="btn btn-soft btn-small" data-crm-action="edit-room" data-id="${r.id}">עריכה</button><button class="btn btn-danger btn-small" data-crm-action="delete-room" data-id="${r.id}">מחיקה</button></div></article>`}).join('')}</div>`:'<div class="empty-state">אין עדיין חדרים. צרו חדרים ואז שייכו אליהם מטיילים.</div>'}`;}
function followupsPanel(tourId){const c=crm(),ids=new Set(c.participants.filter(p=>p.tourId===tourId).map(p=>p.id)),rows=c.followUps.filter(f=>ids.has(f.participantId)).sort((a,b)=>String(a.dueAt).localeCompare(String(b.dueAt)));return `<div class="panel-head"><div><h3>מעקבים וחזרות</h3><p class="muted">כדי ששום הבטחה לחזור למטייל לא תלך לאיבוד.</p></div><button class="btn btn-gold btn-small" data-crm-action="add-followup" data-tour-id="${e(tourId)}">+ מעקב</button></div>${rows.length?`<div class="followup-list">${rows.map(f=>{const p=findParticipant(f.participantId);return `<article class="followup ${f.status}"><div><strong>${e(p?participantName(p):'')}</strong><span>${taskKind(f.kind)} · ${dt(f.dueAt)}</span><p>${e(f.note)}</p></div><div class="actions">${f.status==='pending'?`<button class="btn btn-gold btn-small" data-crm-action="complete-followup" data-id="${f.id}">בוצע</button>`:''}<button class="btn btn-danger btn-small" data-crm-action="delete-followup" data-id="${f.id}">מחיקה</button></div></article>`}).join('')}</div>`:'<div class="empty-state">אין מעקבים לטיול הזה.</div>'}`;}
function tasksPanel(tourId){const rows=crm().tasks.filter(t=>t.tourId===tourId).sort((a,b)=>String(a.dueDate||'9999').localeCompare(String(b.dueDate||'9999')));return `<div class="panel-head"><div><h3>צ׳קליסט הכנה לטיול</h3><p class="muted">משימות מול ספקים, קבוצה, חוברות ומסמכים.</p></div><button class="btn btn-gold btn-small" data-crm-action="add-task" data-tour-id="${e(tourId)}">+ משימה</button></div>${rows.length?`<div class="task-list">${rows.map(t=>`<article class="task-row ${t.status}"><div><strong>${e(t.title)}</strong><span>${t.dueDate?fmt(t.dueDate):'ללא תאריך'} · ${t.priority==='high'?'דחוף':t.priority==='low'?'נמוך':'רגיל'}</span>${t.notes?`<p>${e(t.notes)}</p>`:''}</div><div class="actions">${t.status==='open'?`<button class="btn btn-gold btn-small" data-crm-action="complete-task" data-id="${t.id}">סיום</button>`:''}<button class="btn btn-soft btn-small" data-crm-action="edit-task" data-id="${t.id}">עריכה</button><button class="btn btn-danger btn-small" data-crm-action="delete-task" data-id="${t.id}">מחיקה</button></div></article>`).join('')}</div>`:'<div class="empty-state">אין עדיין משימות.</div>'}`;}
function docsPanel(tourId){const rows=crm().documents.filter(x=>x.tourId===tourId).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));return `<div class="panel-head"><div><h3>מסמכי הטיול</h3><p class="muted">קבצים פנימיים נשמרים ב־Storage פרטי ונפתחים בקישור זמני בלבד.</p></div><button class="btn btn-gold btn-small" data-crm-action="upload-document" data-tour-id="${e(tourId)}">+ העלאת מסמך</button></div><div class="privacy-guardrail compact"><strong>לא מעלים דרכונים או מידע רפואי אלא אם יש צורך תפעולי אמיתי.</strong> אם כן, מצמצמים את המידע ושומרים אותו רק לזמן הנדרש.</div>${rows.length?`<div class="document-list">${rows.map(x=>`<article><div><strong>${e(x.title)}</strong><span>${e(x.fileName)} · ${Math.round(x.fileSize/1024)}KB</span></div><div class="actions"><button class="btn btn-soft btn-small" data-crm-action="open-document" data-id="${x.id}">פתיחה</button><button class="btn btn-danger btn-small" data-crm-action="delete-document" data-id="${x.id}">מחיקה</button></div></article>`).join('')}</div>`:'<div class="empty-state">לא הועלו מסמכים לטיול.</div>'}`;}
function groupsPanel(tourId){const rows=crm().bookingGroups.filter(x=>x.tourId===tourId);return `<div class="booking-groups-mini"><div class="panel-head"><div><h3>זוגות ומשפחות</h3><p class="muted">קישור מטיילים יחד לצורך ניהול וחדרים.</p></div><button class="btn btn-soft btn-small" data-crm-action="add-group" data-tour-id="${e(tourId)}">+ קבוצה</button></div>${rows.length?`<div class="chip-row">${rows.map(g=>`<span class="crm-chip">${e(g.name||'קבוצה')} · ${e(g.groupType)} <button type="button" aria-label="עריכת ${e(g.name)}" data-crm-action="edit-group" data-id="${g.id}">עריכה</button><button type="button" aria-label="מחיקת ${e(g.name)}" data-crm-action="delete-group" data-id="${g.id}">×</button></span>`).join('')}</div>`:'<small class="muted">עדיין לא הוגדרו זוגות או משפחות.</small>'}</div>`;}
function renderOperations(d){const c=crm();if(!c.loaded)return loading();const list=activeTours(d);if(!list.length)return `<div class="panel-head"><div><span class="section-kicker">תפעול</span><h1>ניהול טיול</h1></div></div><section class="panel empty-state">כדי לנהל מטיילים צריך קודם ליצור טיול שאינו "מחקר ספק".</section>`;const tid=ensureTour(d),t=findTour(d,tid);let body='';if(opsTab==='participants')body=`${participantRows(d,tid)}${groupsPanel(tid)}`;if(opsTab==='payments')body=paymentsPanel(tid);if(opsTab==='rooming')body=roomingPanel(tid);if(opsTab==='followups')body=followupsPanel(tid);if(opsTab==='tasks')body=tasksPanel(tid);if(opsTab==='documents')body=docsPanel(tid);return `<div class="panel-head crm-operations-head"><div><span class="section-kicker">תפעול הטיול</span><h1>${e(t?.title||'ניהול טיול')}</h1><p class="muted">נרשמים, יתרות, חדרים, מעקבים, משימות ומסמכים במקום אחד.</p></div><div class="actions"><button class="btn btn-outline" data-crm-action="export-tour" data-tour-id="${e(tid)}">ייצוא Excel</button><button class="btn btn-gold" data-crm-action="add-participant" data-tour-id="${e(tid)}">+ שיוך מטייל</button></div></div><div class="crm-tour-picker"><label>בחרי טיול</label>${tourSelect(d)}</div>${tourStats(d,tid)}${opsTabs()}<section class="panel crm-ops-panel">${body}</section>`;}

function travelerProfile(d,t){
  const c=crm(),ps=c.participants.filter(p=>p.travelerId===t.id).sort((a,b)=>String(findTour(d,b.tourId)?.start||'').localeCompare(String(findTour(d,a.tourId)?.start||''))),fus=c.followUps.filter(f=>f.travelerId===t.id||ps.some(p=>p.id===f.participantId)).filter(f=>f.status==='pending').sort((a,b)=>String(a.dueAt).localeCompare(String(b.dueAt)));
  const contacts=(c.contactLog||[]).filter(x=>x.travelerId===t.id).sort((a,b)=>String(b.occurredAt).localeCompare(String(a.occurredAt))).slice(0,20);
  const history=ps.length?ps.map(p=>{const tour=findTour(d,p.tourId)||{},got=paidFor(p.id),bal=p.agreedPrice==null?'':Math.max(0,Number(p.agreedPrice)-got);return `<tr><td><strong>${e(tour.title||p.tourId)}</strong><small>${fmt(tour.start)}${tour.end?` – ${fmt(tour.end)}`:''}</small></td><td>${statusText(p.status)}</td><td>${p.agreedPrice!=null?`${money(got,p.currency)}<small>${bal?`יתרה ${money(bal,p.currency)}`:'ללא יתרה'}</small>`:'—'}</td></tr>`;}).join(''):'<tr><td colspan="3">אין עדיין היסטוריית טיולים.</td></tr>';
  const contactHtml=contacts.length?`<div class="contact-timeline">${contacts.map(x=>`<article><div><strong>${contactChannel(x.channel)}</strong><span>${contactDirection(x.direction)} · ${dt(x.occurredAt)}</span></div>${x.summary?`<p>${e(x.summary)}</p>`:''}<button class="btn btn-danger btn-small" data-crm-action="delete-contact" data-id="${x.id}">מחיקה</button></article>`).join('')}</div>`:'<p class="muted">עדיין אין היסטוריית קשר.</p>';
  modal(`<div class="modal-head"><div><span class="section-kicker">כרטיס מטייל</span><h2>${e(t.fullName)}</h2></div><button class="modal-close" data-action="close-modal" aria-label="סגירת החלון">×</button></div><div class="traveler-profile-head"><div><strong>${e(t.phone)}</strong>${t.email?`<span>${e(t.email)}</span>`:''}${t.city?`<span>${e(t.city)}</span>`:''}</div><div class="actions"><button class="btn btn-soft btn-small" data-crm-action="traveler-whatsapp" data-id="${t.id}">WhatsApp</button><button class="btn btn-soft btn-small" data-crm-action="log-contact" data-traveler-id="${t.id}">רישום קשר</button><button class="btn btn-outline btn-small" data-crm-action="edit-traveler" data-id="${t.id}">עריכה</button><button class="btn btn-gold btn-small" data-crm-action="add-participant" data-traveler-id="${t.id}">שייך לטיול</button></div></div>${t.tags?.length?`<div class="chip-row">${t.tags.map(x=>`<span class="crm-chip">${e(x)}</span>`).join('')}</div>`:''}${t.notes?`<div class="privacy-guardrail"><strong>הערות:</strong> ${e(t.notes)}</div>`:''}<h3>היסטוריית טיולים</h3><div class="table-wrap"><table class="table"><thead><tr><th scope="col">טיול</th><th scope="col">סטטוס</th><th scope="col">תשלומים</th></tr></thead><tbody>${history}</tbody></table></div><div class="profile-section-head"><h3>היסטוריית קשר</h3><button class="btn btn-soft btn-small" data-crm-action="log-contact" data-traveler-id="${t.id}">+ רישום קשר</button></div>${contactHtml}<h3>מעקבים פתוחים</h3>${fus.length?`<div class="followup-list">${fus.map(f=>`<div class="followup"><div><strong>${taskKind(f.kind)}</strong><span>${dt(f.dueAt)}</span><p>${e(f.note)}</p></div></div>`).join('')}</div>`:'<p class="muted">אין מעקבים פתוחים.</p>'}`);
}
function travelerForm(t=null){const x=t||{fullName:'',phone:'',email:'',city:'',notes:'',tags:[],marketingConsent:false};modal(`<div class="modal-head"><div><span class="section-kicker">מאגר מטיילים</span><h2>${t?'עריכת מטייל':'מטייל חדש'}</h2></div><button class="modal-close" data-action="close-modal">×</button></div><form id="crmTravelerForm" class="admin-form"><input type="hidden" name="id" value="${e(x.id||'')}"><div class="field"><label>שם מלא</label><input required name="fullName" value="${e(x.fullName)}" autocomplete="name"></div><div class="field"><label>טלפון</label><input required name="phone" value="${e(x.phone)}" inputmode="tel" autocomplete="tel"></div><div class="field"><label>אימייל</label><input type="email" name="email" value="${e(x.email||'')}" autocomplete="email"></div><div class="field"><label>עיר</label><input name="city" value="${e(x.city||'')}"></div><div class="field full"><label>תגיות</label><input name="tags" value="${e((x.tags||[]).join(', '))}" placeholder="למשל: לקוח חוזר, מתעניין ביפן"></div><div class="field full"><label>הערות פנימיות</label><textarea name="notes" maxlength="5000">${e(x.notes||'')}</textarea><small>עדיף לא לרשום כאן מידע רפואי, מספרי דרכון או מידע רגיש שאינו נדרש.</small></div><label class="field full consent-row"><input type="checkbox" name="marketingConsent" ${x.marketingConsent?'checked':''}><span>המטייל אישר קבלת עדכונים על טיולים עתידיים.</span></label><button class="btn btn-gold full">שמירה</button></form>`);}
function participantForm(d,p=null,preset={}){const c=crm(),tid=p?.tourId||preset.tourId||ensureTour(d),travelerId=p?.travelerId||preset.travelerId||'',groups=c.bookingGroups.filter(g=>g.tourId===tid);modal(`<div class="modal-head"><div><span class="section-kicker">שיוך לטיול</span><h2>${p?'פרטי משתתף':'הוספת מטייל לטיול'}</h2></div><button class="modal-close" data-action="close-modal">×</button></div><form id="crmParticipantForm" class="admin-form"><input type="hidden" name="id" value="${e(p?.id||'')}"><input type="hidden" name="sourceInquiryId" value="${e(p?.sourceInquiryId||'')}"><div class="field full"><label>טיול</label><select required name="tourId">${activeTours(d).map(t=>`<option value="${e(t.id)}" ${t.id===tid?'selected':''}>${e(t.title)} · ${fmt(t.start)}</option>`).join('')}</select></div><div class="field full"><label>מטייל/ת</label><select required name="travelerId"><option value="">בחירה</option>${c.travelers.filter(t=>!t.archived).map(t=>`<option value="${t.id}" ${t.id===travelerId?'selected':''}>${e(t.fullName)} · ${e(t.phone)}</option>`).join('')}</select><small>אם האדם עדיין לא במאגר, צרו אותו תחילה במסך "מטיילים".</small></div><div class="field"><label>סטטוס</label><select name="status">${['interested','contacted','pending','registered','deposit','paid','waitlist','cancelled'].map(s=>`<option value="${s}" ${p?.status===s?'selected':''}>${statusText(s)}</option>`).join('')}</select></div><div class="field"><label>זוג / משפחה</label><select name="bookingGroupId"><option value="">ללא</option>${groups.map(g=>`<option value="${g.id}" ${p?.bookingGroupId===g.id?'selected':''}>${e(g.name)}</option>`).join('')}</select></div><div class="field"><label>מחיר שסוכם למעקב</label><input name="agreedPrice" type="number" min="0" step="0.01" value="${e(p?.agreedPrice??'')}"></div><div class="field"><label>מטבע</label><select name="currency">${['ILS','EUR','USD'].map(x=>`<option ${p?.currency===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>נקודת איסוף</label><input name="pickupPoint" value="${e(p?.pickupPoint||'')}"></div><div class="field"><label>בקשת חדר</label><input name="roomRequest" value="${e(p?.roomRequest||'')}" placeholder="למשל: זוגי / יחיד"></div><div class="field full"><label>הערות תפעוליות</label><textarea name="operationalNotes">${e(p?.operationalNotes||'')}</textarea></div><button class="btn btn-gold full">שמירה</button></form>`);}
function paymentForm(p){const t=findTraveler(p.travelerId);modal(`<div class="modal-head"><div><span class="section-kicker">מעקב תשלומים</span><h2>רישום תשלום · ${e(t?.fullName||'')}</h2></div><button class="modal-close" data-action="close-modal">×</button></div><form id="crmPaymentForm" class="admin-form"><input type="hidden" name="participantId" value="${p.id}"><input type="hidden" name="currency" value="${e(p.currency||'ILS')}"><div class="field"><label>סכום</label><input required type="number" name="amount" min="0.01" step="0.01"></div><div class="field"><label>מטבע</label><input value="${e(p.currency||'ILS')}" disabled></div><div class="field"><label>תאריך</label><input required type="date" name="paidOn" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>אופן</label><select name="method"><option value="bank_transfer">העברה בנקאית</option><option value="cash">מזומן</option><option value="supplier">תשלום אצל הספק</option><option value="check">צ׳ק</option><option value="other">אחר</option></select></div><div class="field full"><label>אסמכתא / תיאור</label><input name="reference" maxlength="160"></div><div class="field full"><label>הערה</label><textarea name="note"></textarea></div><div class="notice full"><strong>אין להזין מספר כרטיס אשראי, CVV או סיסמה בנקאית.</strong> המערכת משמשת למעקב סכומים בלבד. אם מחיר הטיול הוא במטבע אחר, יש לעדכן קודם את פרטי המשתתף.</div><button class="btn btn-gold full">שמירת תשלום</button></form>`);}
function roomForm(r=null,tourId=''){const x=r||{tourId,roomLabel:'',roomType:'double',notes:''};modal(`<div class="modal-head"><h2>${r?'עריכת חדר':'חדר חדש'}</h2><button class="modal-close" data-action="close-modal">×</button></div><form id="crmRoomForm" class="admin-form"><input type="hidden" name="id" value="${e(x.id||'')}"><input type="hidden" name="tourId" value="${e(x.tourId)}"><div class="field"><label>מספר / שם חדר</label><input required name="roomLabel" value="${e(x.roomLabel)}" placeholder="למשל: 204 או כהן"></div><div class="field"><label>סוג</label><select name="roomType">${['single','double','twin','triple','family','other'].map(s=>`<option value="${s}" ${x.roomType===s?'selected':''}>${roomType(s)}</option>`).join('')}</select></div><div class="field full"><label>הערה</label><textarea name="notes">${e(x.notes||'')}</textarea></div><button class="btn btn-gold full">שמירה</button></form>`);}
function assignRoomForm(p){const rooms=crm().rooms.filter(r=>r.tourId===p.tourId),current=roomFor(p.id);modal(`<div class="modal-head"><h2>שיבוץ חדר · ${e(participantName(p))}</h2><button class="modal-close" data-action="close-modal">×</button></div><form id="crmAssignRoomForm" class="admin-form"><input type="hidden" name="participantId" value="${p.id}"><div class="field full"><label>חדר</label><select name="roomId"><option value="">ללא שיבוץ</option>${rooms.map(r=>`<option value="${r.id}" ${current?.id===r.id?'selected':''}>${e(r.roomLabel)} · ${roomType(r.roomType)}</option>`).join('')}</select></div><button class="btn btn-gold full">שמירה</button></form>`);}
function followupForm(d,preset={}){const tid=preset.tourId||ensureTour(d),ps=crm().participants.filter(p=>p.tourId===tid);modal(`<div class="modal-head"><h2>מעקב חדש</h2><button class="modal-close" data-action="close-modal">×</button></div><form id="crmFollowupForm" class="admin-form"><div class="field full"><label>מטייל/ת</label><select required name="participantId">${ps.map(p=>`<option value="${p.id}" ${p.id===preset.participantId?'selected':''}>${e(participantName(p))}</option>`).join('')}</select></div><div class="field"><label>מועד</label><input required type="datetime-local" name="dueAt" value="${localDateTimeInput(new Date(Date.now()+86400000))}"></div><div class="field"><label>סוג</label><select name="kind"><option value="follow_up">חזרה למטייל</option><option value="payment">תשלום</option><option value="documents">מסמכים</option><option value="supplier">ספק</option><option value="other">אחר</option></select></div><div class="field full"><label>מה צריך לעשות?</label><textarea required name="note"></textarea></div><button class="btn btn-gold full">שמירה</button></form>`);}
function taskForm(t=null,tourId=''){const x=t||{tourId,title:'',dueDate:'',priority:'normal',status:'open',notes:''};modal(`<div class="modal-head"><h2>${t?'עריכת משימה':'משימה חדשה'}</h2><button class="modal-close" data-action="close-modal">×</button></div><form id="crmTaskForm" class="admin-form"><input type="hidden" name="id" value="${e(x.id||'')}"><input type="hidden" name="tourId" value="${e(x.tourId)}"><div class="field full"><label>משימה</label><input required name="title" value="${e(x.title)}"></div><div class="field"><label>תאריך יעד</label><input type="date" name="dueDate" value="${e(x.dueDate||'')}"></div><div class="field"><label>עדיפות</label><select name="priority"><option value="normal" ${x.priority==='normal'?'selected':''}>רגילה</option><option value="high" ${x.priority==='high'?'selected':''}>דחופה</option><option value="low" ${x.priority==='low'?'selected':''}>נמוכה</option></select></div><div class="field full"><label>הערות</label><textarea name="notes">${e(x.notes||'')}</textarea></div><button class="btn btn-gold full">שמירה</button></form>`);}
function groupForm(tourId,g=null){modal(`<div class="modal-head"><h2>${g?'עריכת':'יצירת'} זוג / משפחה</h2><button class="modal-close" data-action="close-modal">×</button></div><form id="crmGroupForm" class="admin-form"><input type="hidden" name="id" value="${e(g?.id||'')}"><input type="hidden" name="tourId" value="${e(g?.tourId||tourId)}"><div class="field"><label>שם קבוצה</label><input required name="name" value="${e(g?.name||'')}" placeholder="למשל: משפחת כהן"></div><div class="field"><label>סוג</label><select name="groupType">${[['couple','זוג'],['family','משפחה'],['friends','חברים'],['single','יחיד'],['other','אחר']].map(([v,l])=>`<option value="${v}" ${g?.groupType===v?'selected':''}>${l}</option>`).join('')}</select></div><div class="field full"><label>הערה</label><textarea name="notes">${e(g?.notes||'')}</textarea></div><button class="btn btn-gold full">שמירה</button></form>`);}
function documentForm(tourId){modal(`<div class="modal-head"><h2>העלאת מסמך פרטי</h2><button class="modal-close" data-action="close-modal">×</button></div><form id="crmDocumentForm" class="admin-form"><input type="hidden" name="tourId" value="${e(tourId)}"><div class="field full"><label>קובץ</label><input required type="file" name="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.csv,.jpg,.jpeg,.png,.webp"></div><div class="field"><label>שם במסך</label><input name="title" placeholder="למשל: Rooming List לספק"></div><div class="field"><label>קטגוריה</label><select name="category"><option value="itinerary">מסלול</option><option value="voucher">שובר</option><option value="rooming">Rooming</option><option value="passenger_list">רשימת נוסעים</option><option value="booklet">חוברת</option><option value="supplier">ספק</option><option value="other">אחר</option></select></div><div class="notice full">הקובץ נשמר ב־Storage פרטי. קישור לצפייה תקף לזמן קצר בלבד.</div><button class="btn btn-gold full">העלאה</button></form>`);}
function convertLeadForm(d,lead){const tid=lead.tourId&&d.tours.some(t=>t.id===lead.tourId)?lead.tourId:ensureTour(d);modal(`<div class="modal-head"><div><span class="section-kicker">פנייה → מטייל</span><h2>הוספת ${e(lead.name)} למאגר</h2></div><button class="modal-close" data-action="close-modal">×</button></div><form id="crmConvertLeadForm" class="admin-form"><input type="hidden" name="inquiryId" value="${e(lead.id)}"><div class="field full"><label>לאיזה טיול לשייך?</label><select required name="tourId">${activeTours(d).map(t=>`<option value="${e(t.id)}" ${t.id===tid?'selected':''}>${e(t.title)} · ${fmt(t.start)}</option>`).join('')}</select></div><div class="notice full">המערכת תחפש קודם את מספר הטלפון במאגר. אם המטייל כבר קיים, היא לא תיצור כפילות אלא תשייך אותו לטיול נוסף.</div><button class="btn btn-gold full">הפוך למטייל</button></form>`);}

function contactForm(d,preset={}){
  const traveler=findTraveler(preset.travelerId),participant=preset.participantId?findParticipant(preset.participantId):null;
  modal(`<div class="modal-head"><div><span class="section-kicker">היסטוריית קשר</span><h2>רישום קשר · ${e(traveler?.fullName||'מטייל/ת')}</h2></div><button class="modal-close" data-action="close-modal" aria-label="סגירת החלון">×</button></div><form id="crmContactForm" class="admin-form"><input type="hidden" name="travelerId" value="${e(traveler?.id||'')}"><input type="hidden" name="participantId" value="${e(participant?.id||'')}"><div class="field"><label>ערוץ</label><select name="channel"><option value="phone">טלפון</option><option value="whatsapp">WhatsApp</option><option value="email">אימייל</option><option value="in_person">פנים אל פנים</option><option value="note">הערה פנימית</option></select></div><div class="field"><label>כיוון</label><select name="direction"><option value="outbound">יצא מחנה</option><option value="inbound">התקבל מהמטייל</option><option value="internal">פנימי</option></select></div><div class="field full"><label>מועד</label><input type="datetime-local" name="occurredAt" value="${localDateTimeInput(new Date())}"></div><div class="field full"><label>סיכום קצר</label><textarea name="summary" maxlength="1000" placeholder="למשל: ביקשה לבדוק חדר יחיד. לחזור ביום ראשון."></textarea><small>לא לשמור כאן מידע רפואי, פרטי דרכון או פרטי תשלום רגישים.</small></div><button class="btn btn-gold full">שמירת רישום</button></form>`);
}

function workbookForTour(d,tourId){
  const c=crm(),tour=findTour(d,tourId),ps=c.participants.filter(p=>p.tourId===tourId),active=ps.filter(p=>p.status!=='cancelled'),ids=new Set(ps.map(p=>p.id));
  const registered=ps.filter(p=>['registered','deposit','paid'].includes(p.status)).length,wait=ps.filter(p=>p.status==='waitlist').length;
  const totals={},balances={}; active.forEach(p=>{const cur=p.currency||'ILS',got=paidFor(p.id);totals[cur]=(totals[cur]||0)+got;if(p.agreedPrice!=null)balances[cur]=(balances[cur]||0)+Math.max(0,Number(p.agreedPrice)-got);});
  const summary=[['סיכום טיול','ערך'],['טיול',tour?.title||''],['יעד',d.destinations.find(x=>x.slug===tour?.destination)?.name||''],['תאריך יציאה',tour?.start||''],['תאריך חזרה',tour?.end||''],['קיבולת',tour?.capacity||''],['משתתפים פעילים',active.length],['נרשמו',registered],['רשימת המתנה',wait],['תשלומים שנרשמו',moneyMap(totals)],['יתרות למעקב',moneyMap(balances)],['נוצר בתאריך',new Date().toLocaleString('he-IL')],['הערה','קובץ זה הוא כלי תפעולי פנימי ואינו אסמכתת תשלום.']];
  const participants=[['שם','טלפון','אימייל','סטטוס','מחיר מוסכם','מטבע','שולם','יתרה','נקודת איסוף','בקשת חדר','חדר','זוג/משפחה','הערות'],...ps.map(p=>{const t=findTraveler(p.travelerId)||{},paid=paidFor(p.id),bal=p.agreedPrice==null?'':Math.max(0,Number(p.agreedPrice)-paid),room=roomFor(p.id),group=groupFor(p.bookingGroupId);return [t.fullName,t.phone,t.email,statusText(p.status),p.agreedPrice==null?'':Number(p.agreedPrice),p.currency,paid,bal,p.pickupPoint,p.roomRequest,room?.roomLabel||'',group?.name||'',p.operationalNotes];})];
  const payments=[['שם','סכום','מטבע','תאריך','אופן','אסמכתא','הערה'],...c.payments.filter(x=>ids.has(x.participantId)).map(x=>{const p=findParticipant(x.participantId);return [p?participantName(p):'',x.amount,x.currency,x.paidOn,paymentMethod(x.method),x.reference,x.note];})];
  const rooming=[['חדר','סוג','מטיילים','טלפונים','הערה'],...c.rooms.filter(r=>r.tourId===tourId).map(r=>{const occ=c.roomOccupants.filter(o=>o.roomId===r.id).map(o=>findParticipant(o.participantId)).filter(Boolean);return [r.roomLabel,roomType(r.roomType),occ.map(p=>participantName(p)).join(', '),occ.map(p=>findTraveler(p.travelerId)?.phone||'').filter(Boolean).join(', '),r.notes];})];
  const followups=[['מטייל','מועד','סוג','משימה','סטטוס'],...c.followUps.filter(f=>ids.has(f.participantId)).map(f=>{const p=findParticipant(f.participantId);return [p?participantName(p):'',dt(f.dueAt),taskKind(f.kind),f.note,f.status==='pending'?'פתוח':f.status==='done'?'בוצע':'בוטל'];})];
  const tasks=[['משימה','תאריך יעד','עדיפות','סטטוס','הערות'],...c.tasks.filter(x=>x.tourId===tourId).map(x=>[x.title,x.dueDate,x.priority==='high'?'דחופה':x.priority==='low'?'נמוכה':'רגילה',x.status==='open'?'פתוחה':x.status==='done'?'בוצעה':'בוטלה',x.notes])];
  const contacts=[['מטייל','ערוץ','כיוון','מועד','סיכום'],...(c.contactLog||[]).filter(x=>x.participantId&&ids.has(x.participantId)).map(x=>{const p=findParticipant(x.participantId);return [p?participantName(p):'',contactChannel(x.channel),contactDirection(x.direction),dt(x.occurredAt),x.summary];})];
  return {filename:`${String(tour?.title||'טיול').replace(/[\/:*?"<>|]/g,'-')}-${new Date().toISOString().slice(0,10)}.xlsx`,sheets:[{name:'סיכום',rows:summary},{name:'משתתפים',rows:participants},{name:'תשלומים',rows:payments},{name:'חדרים',rows:rooming},{name:'מעקבים',rows:followups},{name:'משימות',rows:tasks},{name:'קשר',rows:contacts}]};
}
function exportTour(d,tourId){const wb=workbookForTour(d,tourId);window.ChanaXLSX.downloadWorkbook(wb.filename,wb.sheets);}
function exportTravelers(){const c=crm(),rows=[['שם','טלפון','אימייל','עיר','מספר טיולים','עדכונים','תגיות','הערות'],...c.travelers.filter(x=>!x.archived).map(t=>[t.fullName,t.phone,t.email,t.city,participantCountForTraveler(t.id),t.marketingConsent?'כן':'לא',(t.tags||[]).join(', '),t.notes])];window.ChanaXLSX.downloadWorkbook(`מאגר-מטיילים-${new Date().toISOString().slice(0,10)}.xlsx`,[{name:'מטיילים',rows}]);}
function exportLeads(d){const rows=[['שם','טלפון','יעד','טיול','מתאריך','עד תאריך','הודעה','סטטוס','אישור עדכונים','תאריך פנייה'],...(d.leads||[]).map(l=>[l.name,l.phone,l.destination,l.tourTitle||'',l.tourStart||'',l.tourEnd||'',l.message,l.status||'new',l.marketingConsent?'כן':'לא',l.createdAt])];window.ChanaXLSX.downloadWorkbook(`פניות-מהאתר-${new Date().toISOString().slice(0,10)}.xlsx`,[{name:'פניות',rows}]);}
function exportCRMJson(d){
  const c=crm(),payload={
    schemaVersion:'chana-tours-crm-2026-08-28-v2',
    exportedAt:new Date().toISOString(),
    notice:'Operational backup. Payment entries are tracking records only; private document binaries remain in Supabase Storage.',
    tours:(d.tours||[]).map(t=>({...t})),
    inquiries:(d.leads||[]).map(x=>({...x})),
    travelers:c.travelers.map(x=>({...x})),
    participants:c.participants.map(x=>({...x})),
    payments:c.payments.map(x=>({...x})),
    bookingGroups:c.bookingGroups.map(x=>({...x})),
    rooms:c.rooms.map(x=>({...x})),
    roomOccupants:c.roomOccupants.map(x=>({...x})),
    followUps:c.followUps.map(x=>({...x})),
    tasks:c.tasks.map(x=>({...x})),
    documents:c.documents.map(x=>({...x})),
    contactLog:(c.contactLog||[]).map(x=>({...x}))
  };
  const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json;charset=utf-8'}),a=document.createElement('a');
  a.href=URL.createObjectURL(blob);a.download=`Chana-Tours-CRM-Backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);
}
function exportAllCRM(d){
  const c=crm(),date=new Date().toISOString().slice(0,10);
  const travelers=[['שם','טלפון','אימייל','עיר','סטטוס מאגר','מספר טיולים','אישור עדכונים','תגיות','הערות'],...c.travelers.map(t=>[t.fullName,t.phone,t.email,t.city,t.archived?'ארכיון':'פעיל',participantCountForTraveler(t.id),t.marketingConsent?'כן':'לא',(t.tags||[]).join(', '),t.notes])];
  const participants=[['טיול','תאריך יציאה','שם','טלפון','סטטוס','מחיר','מטבע','שולם','יתרה','איסוף','בקשת חדר','חדר','זוג/משפחה','הערות'],...c.participants.map(p=>{const tr=findTraveler(p.travelerId)||{},tour=findTour(d,p.tourId)||{},got=paidFor(p.id),bal=p.agreedPrice==null?'':Math.max(0,Number(p.agreedPrice)-got),room=roomFor(p.id),group=groupFor(p.bookingGroupId);return [tour.title||p.tourId,tour.start||'',tr.fullName,tr.phone,statusText(p.status),p.agreedPrice??'',p.currency,got,bal,p.pickupPoint,p.roomRequest,room?.roomLabel||'',group?.name||'',p.operationalNotes];})];
  const payments=[['טיול','מטייל','סכום','מטבע','תאריך','אופן','אסמכתא','הערה'],...c.payments.map(x=>{const p=findParticipant(x.participantId),tour=p&&findTour(d,p.tourId);return [tour?.title||'',p?participantName(p):'',x.amount,x.currency,x.paidOn,paymentMethod(x.method),x.reference,x.note];})];
  const leads=[['שם','טלפון','יעד','טיול','מתאריך','עד תאריך','הודעה','סטטוס','אישור עדכונים','תאריך פנייה'],...(d.leads||[]).map(l=>[l.name,l.phone,l.destination,l.tourTitle||'',l.tourStart||'',l.tourEnd||'',l.message,l.status||'new',l.marketingConsent?'כן':'לא',l.createdAt])];
  const rooms=[['טיול','חדר','סוג','מטיילים','הערה'],...c.rooms.map(r=>{const tour=findTour(d,r.tourId),names=c.roomOccupants.filter(o=>o.roomId===r.id).map(o=>{const p=findParticipant(o.participantId);return p?participantName(p):'';}).filter(Boolean).join(', ');return [tour?.title||'',r.roomLabel,roomType(r.roomType),names,r.notes];})];
  const followups=[['טיול','מטייל','מועד','סוג','משימה','סטטוס'],...c.followUps.map(f=>{const p=findParticipant(f.participantId),tour=p&&findTour(d,p.tourId);return [tour?.title||'',p?participantName(p):'',dt(f.dueAt),taskKind(f.kind),f.note,f.status];})];
  const tasks=[['טיול','משימה','תאריך יעד','עדיפות','סטטוס','הערות'],...c.tasks.map(x=>[findTour(d,x.tourId)?.title||'',x.title,x.dueDate,x.priority,x.status,x.notes])];
  const documents=[['טיול','שם','קטגוריה','שם קובץ','גודל KB','תאריך'],...c.documents.map(x=>[findTour(d,x.tourId)?.title||'',x.title,x.category,x.fileName,Math.round((x.fileSize||0)/1024),dt(x.createdAt)])];
  const contacts=[['מטייל','טיול','ערוץ','כיוון','מועד','סיכום'],...(c.contactLog||[]).map(x=>{const t=findTraveler(x.travelerId),p=x.participantId&&findParticipant(x.participantId),tour=p&&findTour(d,p.tourId);return [t?.fullName||'',tour?.title||'',contactChannel(x.channel),contactDirection(x.direction),dt(x.occurredAt),x.summary];})];
  window.ChanaXLSX.downloadWorkbook(`Chana-Tours-CRM-Backup-${date}.xlsx`,[{name:'מטיילים',rows:travelers},{name:'משתתפים',rows:participants},{name:'תשלומים',rows:payments},{name:'פניות',rows:leads},{name:'חדרים',rows:rooms},{name:'מעקבים',rows:followups},{name:'משימות',rows:tasks},{name:'מסמכים',rows:documents},{name:'היסטוריית קשר',rows:contacts}]);
}

async function handleClick(btn,action){
  const d=U().getData();
  try{
    if(action==='convert-lead'){const l=(d.leads||[]).find(x=>x.id===btn.dataset.id);if(l)convertLeadForm(d,l);return true;}
    const a=btn.dataset.crmAction;if(!a)return false;
    if(a==='refresh-crm'){await B().loadCRM();refresh();toast('המאגר עודכן');return true;}
    if(a==='add-traveler'){travelerForm();return true;}
    if(a==='traveler-profile'){const t=findTraveler(btn.dataset.id);if(t)travelerProfile(d,t);return true;}
    if(a==='edit-traveler'){travelerForm(findTraveler(btn.dataset.id));return true;}
    if(a==='archive-traveler'){if(confirm('להעביר את המטייל/ת לארכיון? המידע לא יימחק.')){await B().archiveTraveler(btn.dataset.id,true);refresh();toast('הועבר לארכיון')}return true;}
    if(a==='restore-traveler'){await B().archiveTraveler(btn.dataset.id,false);refresh();toast('המטייל/ת הוחזר/ה למאגר');return true;}
    if(a==='erase-traveler'){if(confirm('מחיקה מלאה מיועדת לבקשת פרטיות מאומתת. אם קיימים רישומי תשלום או טיול פעיל המערכת תחסום אותה. להמשיך?')){try{await B().eraseTraveler(btn.dataset.id);refresh();toast('המידע נמחק')}catch(err){toast('לא ניתן למחוק: קיימים רישומים פעילים או פיננסיים שיש לבדוק')}}return true;}
    if(a==='toggle-archive'){showArchived=!showArchived;refresh();return true;}
    if(a==='traveler-whatsapp'){const t=findTraveler(btn.dataset.id),n=normalizeWa(t?.phone);if(n){B().logContact({travelerId:t.id,channel:'whatsapp',direction:'outbound',summary:'פתיחת שיחת WhatsApp מהמערכת'}).catch(console.warn);window.open(`https://wa.me/${n}?text=${encodeURIComponent(`שלום ${t.fullName}, כאן חנה.`)}`,'_blank','noopener');}return true;}
    if(a==='log-contact'){const t=findTraveler(btn.dataset.travelerId||btn.dataset.id);if(t)contactForm(d,{travelerId:t.id,participantId:btn.dataset.participantId||''});return true;}
    if(a==='delete-contact'){if(confirm('למחוק את רישום הקשר?')){await B().deleteContact(btn.dataset.id);refresh();toast('רישום הקשר נמחק')}return true;}
    if(a==='participant-whatsapp'){const p=findParticipant(btn.dataset.id),t=p&&findTraveler(p.travelerId),n=normalizeWa(t?.phone),tour=p&&findTour(d,p.tourId);if(n){B().logContact({travelerId:t.id,participantId:p.id,channel:'whatsapp',direction:'outbound',summary:`פתיחת שיחת WhatsApp לגבי ${tour?.title||'הטיול'}`}).catch(console.warn);window.open(`https://wa.me/${n}?text=${encodeURIComponent(`שלום ${t.fullName}, כאן חנה. אני חוזרת אליך לגבי ${tour?.title||'הטיול'}.`)}`,'_blank','noopener');}return true;}
    if(a==='add-participant'){participantForm(d,null,{tourId:btn.dataset.tourId||activeTourId,travelerId:btn.dataset.travelerId||''});return true;}
    if(a==='edit-participant'){participantForm(d,findParticipant(btn.dataset.id));return true;}
    if(a==='add-payment'){const p=findParticipant(btn.dataset.id);if(p)paymentForm(p);return true;}
    if(a==='delete-payment'){if(confirm('למחוק את רישום התשלום?')){await B().deletePayment(btn.dataset.id);refresh();toast('התשלום נמחק')}return true;}
    if(a==='add-room'){roomForm(null,btn.dataset.tourId||activeTourId);return true;}
    if(a==='edit-room'){roomForm(crm().rooms.find(x=>x.id===btn.dataset.id));return true;}
    if(a==='delete-room'){if(confirm('למחוק את החדר? השיבוצים אליו יוסרו.')){await B().deleteRoom(btn.dataset.id);refresh()}return true;}
    if(a==='assign-room'){const p=findParticipant(btn.dataset.id);if(p)assignRoomForm(p);return true;}
    if(a==='add-followup'){followupForm(d,{tourId:btn.dataset.tourId||activeTourId,participantId:btn.dataset.participantId||''});return true;}
    if(a==='complete-followup'){await B().completeFollowUp(btn.dataset.id);refresh();toast('סומן כבוצע');return true;}
    if(a==='delete-followup'){if(confirm('למחוק את המעקב?')){await B().deleteFollowUp(btn.dataset.id);refresh()}return true;}
    if(a==='add-task'){taskForm(null,btn.dataset.tourId||activeTourId);return true;}
    if(a==='edit-task'){taskForm(crm().tasks.find(x=>x.id===btn.dataset.id));return true;}
    if(a==='complete-task'){const t=crm().tasks.find(x=>x.id===btn.dataset.id);if(t){await B().saveTask({...t,status:'done'});refresh();toast('המשימה הושלמה')}return true;}
    if(a==='delete-task'){if(confirm('למחוק את המשימה?')){await B().deleteTask(btn.dataset.id);refresh()}return true;}
    if(a==='add-group'){groupForm(btn.dataset.tourId||activeTourId);return true;}
    if(a==='edit-group'){const g=crm().bookingGroups.find(x=>x.id===btn.dataset.id);if(g)groupForm(g.tourId,g);return true;}
    if(a==='delete-group'){if(confirm('למחוק את הקבוצה? המשתתפים יישארו בטיול ללא שיוך לקבוצה.')){await B().deleteBookingGroup(btn.dataset.id);refresh();toast('הקבוצה נמחקה')}return true;}
    if(a==='upload-document'){documentForm(btn.dataset.tourId||activeTourId);return true;}
    if(a==='open-document'){const doc=crm().documents.find(x=>x.id===btn.dataset.id);if(doc)await B().openDocument(doc);return true;}
    if(a==='delete-document'){const doc=crm().documents.find(x=>x.id===btn.dataset.id);if(doc&&confirm('למחוק את המסמך מהאחסון הפרטי?')){await B().deleteDocument(doc);refresh()}return true;}
    if(a==='ops-tab'){opsTab=btn.dataset.tab||'participants';refresh();return true;}
    if(a==='export-tour'){exportTour(d,btn.dataset.tourId||activeTourId);toast('קובץ Excel הוכן');return true;}
    if(a==='export-travelers'){exportTravelers();toast('קובץ Excel הוכן');return true;}
    if(a==='export-crm-backup'){exportAllCRM(d);toast('גיבוי Excel מלא הוכן');return true;}
    if(a==='export-crm-json'){exportCRMJson(d);toast('גיבוי CRM ל-JSON הוכן');return true;}
    if(a==='cleanup-old-history'){if(!confirm('למחוק היסטוריית קשר ומעקבים שהושלמו לפני יותר מ-5 שנים? הפעולה אינה מוחקת מטיילים או תשלומים.'))return true;const r=await B().cleanupOldOperationalHistory();refresh();toast(`נוקו ${Number(r?.contacts||0)} רשומות קשר ו-${Number(r?.followups||0)} מעקבים`);return true;}
  }catch(err){console.error(err);toast('הפעולה נכשלה. בדקו את החיבור ונסו שוב.');return true;}
  return false;
}
async function handleSubmit(form){
  const d=U().getData(),fd=Object.fromEntries(new FormData(form));
  try{
    if(form.id==='crmTravelerForm'){await B().saveTraveler({...fd,tags:String(fd.tags||'').split(',').map(x=>x.trim()).filter(Boolean),marketingConsent:form.elements.marketingConsent?.checked});close();refresh();toast('המטייל נשמר');return true;}
    if(form.id==='crmParticipantForm'){await B().saveParticipant({...fd,bookingGroupId:fd.bookingGroupId||null,sourceInquiryId:fd.sourceInquiryId||null,agreedPrice:fd.agreedPrice||null});close();activeTourId=fd.tourId;refresh();toast('השיוך נשמר');return true;}
    if(form.id==='crmPaymentForm'){await B().addPayment(fd);close();refresh();toast('התשלום נרשם');return true;}
    if(form.id==='crmRoomForm'){await B().saveRoom(fd);close();refresh();toast('החדר נשמר');return true;}
    if(form.id==='crmAssignRoomForm'){await B().assignRoom(fd.participantId,fd.roomId||null);close();refresh();toast('השיבוץ נשמר');return true;}
    if(form.id==='crmFollowupForm'){await B().saveFollowUp({...fd,dueAt:new Date(fd.dueAt).toISOString()});close();refresh();toast('המעקב נשמר');return true;}
    if(form.id==='crmTaskForm'){const old=fd.id?crm().tasks.find(x=>x.id===fd.id):null;await B().saveTask({...old,...fd,status:old?.status||'open'});close();refresh();toast('המשימה נשמרה');return true;}
    if(form.id==='crmGroupForm'){await B().saveBookingGroup(fd);close();refresh();toast('הקבוצה נשמרה');return true;}
    if(form.id==='crmDocumentForm'){const file=form.elements.file.files[0];if(!file)return true;await B().uploadDocument(file,{tourId:fd.tourId,title:fd.title||file.name,category:fd.category});close();refresh();toast('המסמך הועלה לאחסון הפרטי');return true;}
    if(form.id==='crmConvertLeadForm'){await B().convertInquiry(fd.inquiryId,fd.tourId);close();activeTourId=fd.tourId;refresh();toast('הפנייה הפכה למטייל בטיול');return true;}
    if(form.id==='crmContactForm'){await B().logContact({...fd,participantId:fd.participantId||null,occurredAt:fd.occurredAt?new Date(fd.occurredAt).toISOString():new Date().toISOString()});close();refresh();toast('רישום הקשר נשמר');return true;}
  }catch(err){console.error(err);const msg=String(err?.message||'');toast(msg.includes('duplicate')||msg.includes('unique')?'המטייל כבר קיים בטיול הזה':'השמירה נכשלה. בדקו את הפרטים ונסו שוב.');return true;}
  return false;
}

document.addEventListener('input',ev=>{if(ev.target.id==='travelerSearch'){const q=String(ev.target.value||'').trim().toLowerCase();document.querySelectorAll('[data-traveler-row]').forEach(r=>r.hidden=q&&!String(r.dataset.search||'').includes(q));}});
document.addEventListener('change',async ev=>{
  if(ev.target.id==='crmTourSelect'){activeTourId=ev.target.value;opsTab='participants';refresh();return;}
  if(ev.target.matches('[data-participant-status]')){const p=findParticipant(ev.target.dataset.participantStatus);if(!p)return;try{await B().saveParticipant({...p,status:ev.target.value});refresh();toast('הסטטוס עודכן');}catch(err){console.error(err);toast('עדכון הסטטוס נכשל');}}
});

window.ChanaCRM={renderSection:(section,d)=>section==='travelers'?renderTravelers(d):section==='operations'?renderOperations(d):'',decorateAdmin,handleClick,handleSubmit,exportLeads,exportAllCRM,exportCRMJson,dashboardSummary};
})();
